set_property PACKAGE_PIN E3 [get_ports Clk]

set_property PACKAGE_PIN T8 [get_ports Switch[7]]
set_property PACKAGE_PIN U8 [get_ports Switch[6]]
set_property PACKAGE_PIN R16 [get_ports Switch[5]]
set_property PACKAGE_PIN T13 [get_ports Switch[4]]
set_property PACKAGE_PIN H6 [get_ports Switch[3]]
set_property PACKAGE_PIN U12 [get_ports Switch[2]]
set_property PACKAGE_PIN U11 [get_ports Switch[1]]
set_property PACKAGE_PIN V10 [get_ports Switch[0]]

set_property PACKAGE_PIN M18 [get_ports FreqIncr]
set_property PACKAGE_PIN M17 [get_ports Save]
set_property PACKAGE_PIN N17 [get_ports PlayPause]
set_property PACKAGE_PIN P17 [get_ports Reset]

set_property PACKAGE_PIN T10 [get_ports LEDSegment[7]]
set_property PACKAGE_PIN R10 [get_ports LEDSegment[6]]
set_property PACKAGE_PIN K16 [get_ports LEDSegment[5]]
set_property PACKAGE_PIN K13 [get_ports LEDSegment[4]]
set_property PACKAGE_PIN P15 [get_ports LEDSegment[3]]
set_property PACKAGE_PIN T11 [get_ports LEDSegment[2]]
set_property PACKAGE_PIN L18 [get_ports LEDSegment[1]]
set_property PACKAGE_PIN H15 [get_ports LEDSegment[0]]

set_property PACKAGE_PIN U13 [get_ports Display[3]]
set_property PACKAGE_PIN K2 [get_ports Display[2]]
set_property PACKAGE_PIN T14 [get_ports Display[1]]
set_property PACKAGE_PIN P14 [get_ports Display[0]]

set_property PACKAGE_PIN V11 [get_ports LEDNote[7]]
set_property PACKAGE_PIN V12 [get_ports LEDNote[6]]
set_property PACKAGE_PIN V14 [get_ports LEDNote[5]]
set_property PACKAGE_PIN V15 [get_ports LEDNote[4]]
set_property PACKAGE_PIN T16 [get_ports LEDNote[3]]
set_property PACKAGE_PIN U14 [get_ports LEDNote[2]]
set_property PACKAGE_PIN T15 [get_ports LEDNote[1]]
set_property PACKAGE_PIN V16 [get_ports LEDNote[0]]

set_property PACKAGE_PIN A11 [get_ports Speaker]


set_property IOSTANDARD LVCMOS33 [get_ports Clk]

set_property IOSTANDARD LVCMOS33 [get_ports Switch[7]]
set_property IOSTANDARD LVCMOS33 [get_ports Switch[6]]
set_property IOSTANDARD LVCMOS33 [get_ports Switch[5]]
set_property IOSTANDARD LVCMOS33 [get_ports Switch[4]]
set_property IOSTANDARD LVCMOS33 [get_ports Switch[3]]
set_property IOSTANDARD LVCMOS33 [get_ports Switch[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Switch[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Switch[0]]

set_property IOSTANDARD LVCMOS33 [get_ports FreqIncr]
set_property IOSTANDARD LVCMOS33 [get_ports Save]
set_property IOSTANDARD LVCMOS33 [get_ports PlayPause]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]

set_property IOSTANDARD LVCMOS33 [get_ports LEDSegment[7]]
set_property IOSTANDARD LVCMOS33 [get_ports LEDSegment[6]]
set_property IOSTANDARD LVCMOS33 [get_ports LEDSegment[5]]
set_property IOSTANDARD LVCMOS33 [get_ports LEDSegment[4]]
set_property IOSTANDARD LVCMOS33 [get_ports LEDSegment[3]]
set_property IOSTANDARD LVCMOS33 [get_ports LEDSegment[2]]
set_property IOSTANDARD LVCMOS33 [get_ports LEDSegment[1]]
set_property IOSTANDARD LVCMOS33 [get_ports LEDSegment[0]]

set_property IOSTANDARD LVCMOS33 [get_ports Display[3]]
set_property IOSTANDARD LVCMOS33 [get_ports Display[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Display[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Display[0]]

set_property IOSTANDARD LVCMOS33 [get_ports LEDNote[7]]
set_property IOSTANDARD LVCMOS33 [get_ports LEDNote[6]]
set_property IOSTANDARD LVCMOS33 [get_ports LEDNote[5]]
set_property IOSTANDARD LVCMOS33 [get_ports LEDNote[4]]
set_property IOSTANDARD LVCMOS33 [get_ports LEDNote[3]]
set_property IOSTANDARD LVCMOS33 [get_ports LEDNote[2]]
set_property IOSTANDARD LVCMOS33 [get_ports LEDNote[1]]
set_property IOSTANDARD LVCMOS33 [get_ports LEDNote[0]]

set_property IOSTANDARD LVCMOS33 [get_ports Speaker]